{% set name = "scikit-hep" %}
{% set version = "2025.1.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7da189fabcbf657f7b273f8e15401f741b78f7e173c1c790c45704922ea27079

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=62.6
  run:
    - awkward ~=2.6.0
    - decaylanguage ~=0.18.0
    - hepstats ~=0.9.0
    - hepunits ~=2.3.0
    - hist ~=2.8.0
    - histoprint ~=2.5.0
    - iminuit ~=2.30.0
    - matplotlib-base >3.4.0
    - mplhep ~=0.3.0
    - numpy >=1.13.1
    - particle ~=0.25.0
    - pylhe ~=0.9.0
    - python >={{ python_min }}
    - resample ~=1.10.0
    - uproot ~=5.4.0
    - vector ~=1.5.0

test:
  imports:
    - skhep
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/scikit-hep/scikit-hep/
  summary: Metapackage of Scikit-HEP project tools for Particle Physics.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scikit-hep/scikit-hep/

extra:
  recipe-maintainers:
    - matthewfeickert
    - chrisburr
    - eduardo-rodrigues
    - henryiii
