{% set name = "scikit-hep" %}
{% set version = "2024.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 157307b4f5c133c3c7c096df949d4add1f4bbe2598df95cf4e39ded93ee58a66

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - awkward ~=2.6.0
    - decaylanguage ~=0.18.0
    - hepstats ~=0.8.0
    - hepunits ~=2.3.0
    - hist ~=2.7.0
    - histoprint ~=2.4.0
    - iminuit ~=2.28.0
    - matplotlib-base >3.4.0
    - mplhep ~=0.3.0
    - numpy >=1.13.1
    - particle ~=0.25.0
    - pylhe ~=0.8.0
    - python >=3.8
    - resample ~=1.10.0
    - uproot ~=5.3.0
    - vector ~=1.4.0

test:
  imports:
    - skhep
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/scikit-hep/
  summary: Metapackage of Scikit-HEP project tools for Particle Physics.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthewfeickert
    - chrisburr
    - eduardo-rodrigues
    - henryiii
